spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://zippy.cvwwmmaa2kpr.ap-northeast-2.rds.amazonaws.com:3306/saen
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: zippy
    password: zippy1357!
#  datasource:
#    url: jdbc:h2:mem:qna;NON_KEYWORDS=USER
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

server:
  servlet:
    session:
      tracking-modes: cookie