spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://mysql:3306/mydb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
#  datasource:
#    url: jdbc:h2:mem:qna;NON_KEYWORDS=USER
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

server:
  servlet:
    session:
      tracking-modes: cookie


